name: Convert HTML CV to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Puppeteer
        run: |
          npm install puppeteer
          echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true" >> $GITHUB_ENV

      - name: Convert CV to PDF
        run: |
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto('https://egorras.github.io/cv', {waitUntil: 'networkidle2'});
            await page.pdf({path: 'cv.pdf', format: 'A4'});
            await browser.close();
          })();
        shell: node {0}

      - name: Upload PDF to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cv
          path: cv.pdf
