name: Convert HTML CV to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: html to pdf
        uses: misaelnieto/web_to_pdf_action@master
        with:
          webPageURL: https://egorras.github.io/cv
          outputFile: cv.pdf
          usePuppeteer: true
          useScreen: true
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
          
      - name: Upload PDF to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: cv.pdf
